name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node 12
      uses: actions/setup-node@v2.1.0

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-tbgmarketing${{ hashFiles('**/package-lock.json') }}
                
    - name: Install Node.js Dependencies
      run: npm install
      
    - run: npm run build
      

deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
    - name: Deploy aws S3
      run: aws s3 sync build/ s3://githubactionss3 --acl public-read --delete
