name: Teste de Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: NodeJS 12
        uses: actions/setup-node@v2.1.0
        
      - name: Install NodeJS modules
        run: npm install
        
      - run: npm run build

      - name: Save buid
        uses: actions/upload-artifact@v2
        with:
          path: build
          name: build
