name: Teste de Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: NodeJS 12
        uses: actions/setup-node@v2.1.0
        
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-tbgmarketing${{ hashFiles('**/package-lock.json') }}
        
      - name: Install NodeJS modules
        run: npm install
        
      - run: npm run build

      - name: Save buid
        uses: actions/upload-artifact@v2
        with:
          path: build
          name: build
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Downloads build folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: files-to-deploy
          
      - name: Deploy AWS S3
        run: aws s3 sync ./files-to-deploy s3://githubactionss3 --acl public-read --delete
